defmodule AshClickhouse.TestResource do
  @moduledoc """
  A simple ClickHouse-backed Ash resource used by integration tests.
  """
  use Ash.Resource,
    data_layer: AshClickhouse.DataLayer,
    domain: AshClickhouse.TestDomain

  import AshClickhouse.DataLayer.Dsl.Macros

  clickhouse do
    table("test_users")
    repo(AshClickhouse.TestRepo)
    database("ash_clickhouse_test")
    engine("MergeTree()")
    order_by("id")
    mutations_sync(1)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:name, :string)
    attribute(:email, :string)
    attribute(:age, :integer)
    create_timestamp(:inserted_at)
  end

  actions do
    defaults([:read, :destroy])

    create :create do
      accept([:name, :email, :age])
    end

    update :update do
      accept([:name, :email, :age])
    end
  end
end

defmodule AshClickhouse.TestPartitionedResource do
  @moduledoc """
  A ClickHouse-backed Ash resource exercising PARTITION BY / PRIMARY KEY /
  SETTINGS DDL generation, used by integration tests.
  """
  use Ash.Resource,
    data_layer: AshClickhouse.DataLayer,
    domain: AshClickhouse.TestDomain

  import AshClickhouse.DataLayer.Dsl.Macros

  clickhouse do
    table("partitioned_users")
    repo(AshClickhouse.TestRepo)
    database("ash_clickhouse_test")
    engine("MergeTree()")
    order_by("id")
    partition_by("toYYYYMM(created_date)")
    primary_key([:id])
    settings("index_granularity = 8192")
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:name, :string)
    attribute(:email, :string)
    attribute(:age, :integer)
    attribute(:created_date, :date, allow_nil?: false)
  end

  actions do
    defaults([:read, :destroy])

    create :create do
      accept([:name, :email, :age, :created_date])
    end
  end
end

defmodule AshClickhouse.TestBulkResource do
  @moduledoc """
  A ClickHouse-backed Ash resource without a timestamp column, used by the
  bulk_create integration tests so inserts do not depend on autogenerated
  timestamps.
  """
  use Ash.Resource,
    data_layer: AshClickhouse.DataLayer,
    domain: AshClickhouse.TestDomain

  import AshClickhouse.DataLayer.Dsl.Macros

  clickhouse do
    table("bulk_users")
    repo(AshClickhouse.TestRepo)
    database("ash_clickhouse_test")
    engine("MergeTree()")
    order_by("id")
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:name, :string)
    attribute(:email, :string)
    attribute(:age, :integer)
  end

  actions do
    defaults([:read, :destroy])

    create :create do
      accept([:name, :email, :age])
    end

    update :update do
      accept([:name, :email, :age])
    end
  end
end

# The domain is defined after its resources so that, when Spark's
# `__verify_spark_dsl__` hook runs for the domain, every referenced resource
# module is already compiled (Elixir >= 1.19 runs `@after_verify` eagerly per
# module while the rest of the file is still compiling).
defmodule AshClickhouse.TestDomain do
  @moduledoc "Test Ash domain for integration tests."
  use Ash.Domain

  resources do
    resource(AshClickhouse.TestResource)
    resource(AshClickhouse.TestPartitionedResource)
    resource(AshClickhouse.TestBulkResource)
  end
end
