defmodule AshClickhouse.DataLayer.Insert do
  @moduledoc """
  Builds the values and SQL fragments used to insert/update rows.

  Extracted from `AshClickhouse.DataLayer` so all persistence value encoding
  (attribute ordering, UUID/decimal/date/time handling, autogenerated primary
  keys) lives in one module and can be reused by the single- and bulk-insert
  paths.
  """

  alias Ash.Resource.Info
  alias AshClickhouse.DataLayer.Dsl
  alias AshClickhouse.DataLayer.Types
  alias AshClickhouse.Identifier

  @doc """
  Builds a `(fields, rows)` pair for bulk insert: quoted column names in the
  resource's attribute declaration order, and each row as a value list aligned
  to that order.
  """
  @spec build_insert_rows([map()], module()) :: {[String.t()], [list()]}
  def build_insert_rows(rows, resource) do
    attrs = Info.attributes(resource)
    attr_map = Map.new(attrs, &{to_string(&1.name), &1})

    fields = Enum.map(attrs, &Identifier.quote_name(&1.name))
    field_atoms = Enum.map(attrs, & &1.name)

    encoded_rows =
      Enum.map(rows, fn row ->
        Enum.map(field_atoms, fn name ->
          case Map.fetch(row, to_string(name)) do
            {:ok, value} ->
              encode_bulk_value(value, Map.fetch!(attr_map, to_string(name)), resource)

            :error ->
              nil
          end
        end)
      end)

    {fields, encoded_rows}
  end

  @doc """
  Builds a fully-formed `INSERT INTO <table> (...) FORMAT JSONCompactEachRow`
  statement from already-built fields.
  """
  @spec insert_statement(String.t(), [String.t()]) :: String.t()
  def insert_statement(qualified, fields) do
    IO.iodata_to_binary([
      "INSERT INTO ",
      qualified,
      " (",
      Enum.join(fields, ", "),
      ") FORMAT JSONCompactEachRow"
    ])
  end

  @doc """
  Encodes a single record's attrs into a row map (string keys → encoded values)
  suitable for the single-insert path.
  """
  @spec attrs_to_row(map(), module()) :: map()
  def attrs_to_row(attrs, resource) do
    uuid_fields = Types.uuid_attribute_names(resource)
    attr_map = attribute_map(resource)

    Enum.reduce(attrs, %{}, fn {key, value}, acc ->
      Map.put(acc, to_string(key), encode_attr_value(key, value, attr_map, uuid_fields))
    end)
  end

  @doc """
  Encodes a single attribute value for a parameterized query.
  """
  @spec encode_attr_value(atom(), term(), map(), MapSet.t()) :: term()
  def encode_attr_value(key, value, attr_map, uuid_fields) do
    cond do
      key in uuid_fields ->
        case Types.uuid_string_to_binary(value) do
          {:ok, bin} -> bin
          _ -> value
        end

      attr = Map.get(attr_map, key) ->
        Types.encode_value(value, attr)

      true ->
        value
    end
  end

  @doc """
  Builds `column = ?` SET clauses and their values (for ALTER TABLE ... UPDATE).
  """
  @spec build_set_clauses(map(), module()) :: {[String.t()], [term()]}
  def build_set_clauses(attrs, resource) do
    uuid_fields = Types.uuid_attribute_names(resource)
    attr_map = attribute_map(resource)

    {clauses, values} =
      Enum.reduce(attrs, {[], []}, fn {key, value}, {cs, vs} ->
        encoded = encode_attr_value(key, value, attr_map, uuid_fields)
        {["#{Identifier.quote_name(to_string(key))} = ?" | cs], [encoded | vs]}
      end)

    {Enum.reverse(clauses), :lists.reverse(values)}
  end

  @doc """
  Builds an AND-joined `col = ?` WHERE clause and its values from a pk map.
  """
  @spec build_where_from_map(map(), module()) :: {String.t(), [term()]}
  def build_where_from_map(pk_map, resource) do
    uuid_fields = Types.uuid_attribute_names(resource)

    {clauses, values} =
      Enum.reduce(pk_map, {[], []}, fn {key, value}, {cs, vs} ->
        {["#{Identifier.quote_name(to_string(key))} = ?" | cs],
         [Types.convert_uuid_param(value, key, uuid_fields) | vs]}
      end)

    {clauses |> Enum.reverse() |> Enum.join(" AND "), :lists.reverse(values)}
  end

  @doc """
  Returns a changeset's `attributes` map with autogenerated values filled in
  for missing primary keys.
  """
  @spec changeset_to_insert_attrs(map(), module()) :: map()
  def changeset_to_insert_attrs(changeset, resource) do
    attrs = changeset.attributes

    Enum.reduce(Info.attributes(resource), attrs, fn attr, acc ->
      if attr.primary_key? and not Map.has_key?(acc, attr.name) and autogenerate_attribute?(attr) do
        Map.put(acc, attr.name, autogenerate_value(attr))
      else
        acc
      end
    end)
  end

  @doc """
  Merges `attributes` and `changes` from a changeset into a single map for the
  SET clause builder.
  """
  @spec changeset_to_update_attrs(map(), term()) :: map()
  def changeset_to_update_attrs(changeset, _resource) do
    attributes = Map.get(changeset, :attributes, %{})
    changes = Map.get(changeset, :changes, %{})
    Map.merge(attributes, changes)
  end

  @doc """
  Builds a map of primary-key column → value from a changeset's current data.
  """
  @spec get_primary_key_from_changeset(map(), module()) :: map()
  def get_primary_key_from_changeset(changeset, resource) do
    source = changeset.data

    Enum.reduce(Info.attributes(resource), %{}, fn attr, acc ->
      if attr.primary_key? do
        case Map.get(source, attr.name) do
          nil -> acc
          val -> Map.put(acc, attr.name, val)
        end
      else
        acc
      end
    end)
  end

  @doc """
  Builds the options forwarded to a bulk insert (async_insert etc.).
  """
  @spec insert_opts(module(), keyword()) :: keyword()
  def insert_opts(resource, opts) do
    merged = Keyword.merge(Dsl.insert_opts(resource), opts)

    merged
    |> maybe_put(:async_insert, Keyword.get(merged, :async_insert))
    |> maybe_put(:wait_for_async_insert, Keyword.get(merged, :wait_for_async_insert))
  end

  # --- internal helpers -----------------------------------------------------

  defp attribute_map(resource) do
    resource
    |> Info.attributes()
    |> Enum.reduce(%{}, fn attr, acc -> Map.put(acc, attr.name, attr) end)
  end

  defp autogenerate_attribute?(attr) do
    Map.get(attr, :autogenerate?) == true or is_function(Map.get(attr, :default))
  end

  defp autogenerate_value(attr) do
    cond do
      attr.type && function_exported?(attr.type, :generator, 1) ->
        constraints = Map.get(attr, :constraints, [])
        attr.type.generator(constraints) |> Enum.at(0)

      attr.type in [Ash.Type.UUID, :uuid] ->
        Ash.UUID.generate()

      true ->
        nil
    end
  end

  defp maybe_put(opts, _key, nil), do: opts
  defp maybe_put(opts, key, value), do: Keyword.put(opts, key, value)

  # Encoding for the JSON bulk insert path. ClickHouse's JSONCompactEachRow
  # expects native JSON values, so we keep UUIDs as their canonical string form
  # and leave maps/arrays as native JSON values. Decimal structs are rendered as
  # numeric strings (Jason does not understand them natively).
  #
  # Date/time values are encoded in the unit ClickHouse expects for the
  # resolved column type:
  #
  #   * `DateTime64(N)` — integer number of microseconds since the Unix epoch
  #     (the column's precision unit is 10^-N seconds).
  #   * `DateTime` — integer number of seconds since the Unix epoch.
  #   * `Date` — integer number of days since 1970-01-01.
  #   * `Time` — the `"HH:MM:SS"` string (time columns are typed `String`).
  defp encode_bulk_value(%DateTime{} = value, attr, _resource),
    do: encode_datetime(value, attr)

  defp encode_bulk_value(%NaiveDateTime{} = value, attr, _resource) do
    case DateTime.from_naive(value, "Etc/UTC") do
      {:ok, dt} -> encode_datetime(dt, attr)
      _ -> value
    end
  end

  defp encode_bulk_value(%Date{} = value, _attr, _resource),
    do: Date.diff(value, ~D[1970-01-01])

  defp encode_bulk_value(%Time{} = value, _attr, _resource),
    do: Time.to_string(value)

  defp encode_bulk_value(%Decimal{} = value, _attr, _resource),
    do: Decimal.to_string(value, :normal)

  defp encode_bulk_value(value, attr, resource) do
    name = attr.name
    uuid_fields = Types.uuid_attribute_names(resource)

    cond do
      name in uuid_fields and is_binary(value) and byte_size(value) == 16 ->
        case Types.uuid_binary_to_string(value) do
          {:ok, str} -> str
          _ -> value
        end

      name in uuid_fields and is_binary(value) and byte_size(value) == 36 ->
        value

      is_map(value) or is_list(value) ->
        value

      true ->
        value
    end
  end

  defp encode_datetime(%DateTime{} = datetime, attr) do
    case Types.resolve_attr_type(attr) do
      "DateTime64(" <> _ -> DateTime.to_unix(datetime, :microsecond)
      _ -> DateTime.to_unix(datetime, :second)
    end
  end
end
