defmodule AshClickhouse.MigrationGenerator do
  @moduledoc "Generates ClickHouse migration files and resource snapshots."

  alias AshClickhouse.DataLayer.Dsl
  alias AshClickhouse.DataLayer.Types
  alias AshClickhouse.Migration
  alias Mix.Tasks.AshClickhouse.Helpers

  @spec generate(keyword()) :: :ok
  def generate(opts \\ []) do
    opts = options(opts)
    resources = opts.resources || Helpers.find_resources()

    results =
      resources
      |> Enum.filter(&Dsl.migrate?/1)
      |> Enum.map(&generate_resource(&1, opts))

    files = Enum.flat_map(results, & &1.files)

    cond do
      files == [] and opts.check ->
        :ok

      files == [] ->
        Mix.shell().info("No changes detected, so no migrations or snapshots have been created.")

      opts.check ->
        raise Ash.Error.Framework.PendingCodegen, diff: files

      opts.dry_run ->
        print_files(files)

      true ->
        Enum.each(files, &write_file/1)

        if not opts.dev do
          cleanup_dev_files(resources, opts)
        end
    end

    :ok
  end

  defp options(opts) do
    %{
      name: Keyword.get(opts, :name),
      dev: Keyword.get(opts, :dev, false),
      dry_run: Keyword.get(opts, :dry_run, false),
      check: Keyword.get(opts, :check, false),
      resources: Keyword.get(opts, :resources),
      migration_path: Keyword.get(opts, :migration_path, "priv/repo/migrations"),
      snapshot_path: Keyword.get(opts, :snapshot_path, "priv/repo/resource_snapshots")
    }
  end

  defp generate_resource(resource, opts) do
    repo = Dsl.repo(resource)
    key = resource_key(resource)
    snapshot_suffix = if opts.dev, do: "_dev", else: ""
    snapshot_path = Path.join(opts.snapshot_path, "#{key}#{snapshot_suffix}.json")
    migration_path = opts.migration_path
    current = snapshot(resource)
    previous = read_snapshot(snapshot_path)
    changed? = previous != current

    if changed? do
      migration = migration_file(resource, repo, current, previous, migration_path, opts)
      snapshot_file = {snapshot_path, Jason.encode!(current, pretty: true) <> "\n"}
      %{files: [migration, snapshot_file]}
    else
      %{files: []}
    end
  end

  defp snapshot(resource) do
    %{
      "resource" => resource_key(resource),
      "table" => AshClickhouse.DataLayer.source(resource),
      "engine" => Dsl.engine(resource),
      "order_by" => Dsl.order_by(resource),
      "partition_by" => Dsl.partition_by(resource),
      "attributes" =>
        resource
        |> Ash.Resource.Info.attributes()
        |> Enum.sort_by(&to_string(&1.name))
        |> Enum.map(fn attr ->
          %{
            "name" => to_string(attr.name),
            "type" => Types.resolve_attr_type(attr),
            "allow_nil?" => attr.allow_nil?
          }
        end),
      "indexes" =>
        Dsl.indexes(resource)
        |> Enum.sort_by(&to_string(&1.name))
        |> Enum.map(fn index ->
          %{
            "name" => to_string(index.name),
            "expression" => index.expression,
            "type" => index.type,
            "granularity" => index.granularity
          }
        end)
    }
  end

  defp migration_file(resource, repo, current, previous, migration_path, opts) do
    {statements, down} = migration_statements(resource, current, previous)
    safe_key = String.replace(resource_key(resource), ".", "_")
    suffix = if opts.dev, do: "_dev", else: ""
    version = timestamp()
    name = opts.name || "migrate"
    filename = "#{version}_#{name}_#{safe_key}#{suffix}.exs"
    module = "AshClickhouse.Migrations.#{Macro.camelize(name)}#{Macro.camelize(safe_key)}"

    contents = """
    defmodule #{module} do
      @moduledoc "Generated by mix ash.codegen."
      use AshClickhouse.Schema

      @impl AshClickhouse.Schema
      def repo, do: #{inspect(repo)}

      @impl AshClickhouse.Schema
      def version, do: "#{version}"

      @impl AshClickhouse.Schema
      def change do
        #{inspect(statements)}
      end

      @impl AshClickhouse.Schema
      def down do
        #{inspect(down)}
      end
    end
    """

    {Path.join(migration_path, filename), contents}
  end

  defp migration_statements(resource, _current, nil) do
    down = [drop_table_cql(resource)]
    {Migration.generate_resource_cql(resource), down}
  end

  defp migration_statements(resource, current, previous) do
    table = AshClickhouse.DataLayer.source(resource)
    old_names = MapSet.new(previous["attributes"] || [], & &1["name"])

    columns =
      current["attributes"]
      |> Enum.reject(&MapSet.member?(old_names, &1["name"]))
      |> Enum.map(fn attr ->
        "ALTER TABLE #{quote_name(table)} ADD COLUMN IF NOT EXISTS #{quote_name(attr["name"])} #{attr["type"]}"
      end)

    column_downs =
      current["attributes"]
      |> Enum.reject(&MapSet.member?(old_names, &1["name"]))
      |> Enum.map(fn attr ->
        "ALTER TABLE #{quote_name(table)} DROP COLUMN IF NOT EXISTS #{quote_name(attr["name"])}"
      end)

    old_indexes = MapSet.new(previous["indexes"] || [], & &1["name"])

    indexes =
      current["indexes"]
      |> Enum.reject(&MapSet.member?(old_indexes, &1["name"]))
      |> Enum.map(fn index ->
        "ALTER TABLE #{quote_name(table)} ADD INDEX IF NOT EXISTS #{quote_name(index["name"])} (#{index["expression"]}) TYPE #{index["type"]} GRANULARITY #{index["granularity"]}"
      end)

    index_downs =
      current["indexes"]
      |> Enum.reject(&MapSet.member?(old_indexes, &1["name"]))
      |> Enum.map(fn index ->
        "ALTER TABLE #{quote_name(table)} DROP INDEX IF NOT EXISTS #{quote_name(index["name"])}"
      end)

    {columns ++ indexes, column_downs ++ index_downs}
  end

  defp drop_table_cql(resource) do
    table = quote_name(AshClickhouse.DataLayer.source(resource))
    database = Dsl.database(resource)

    qualified =
      case database do
        nil -> table
        db -> "#{quote_name(db)}.#{table}"
      end

    "DROP TABLE IF EXISTS #{qualified}"
  end

  defp read_snapshot(path) do
    case File.read(path) do
      {:ok, contents} -> Jason.decode!(contents)
      {:error, :enoent} -> nil
    end
  end

  defp write_file({path, contents}) do
    path |> Path.dirname() |> File.mkdir_p!()
    File.write!(path, contents)
    Mix.shell().info("* creating #{path}")
  end

  defp print_files(files) do
    Enum.each(files, fn {path, contents} ->
      Mix.shell().info("--- #{path} ---\n#{contents}")
    end)
  end

  defp cleanup_dev_files(resources, opts) do
    resources
    |> Enum.map(&resource_key/1)
    |> Enum.each(fn key ->
      File.rm(Path.join(opts.snapshot_path, "#{key}_dev.json"))

      opts.migration_path
      |> Path.join("*_#{String.replace(key, ".", "_")}_dev.exs")
      |> Path.wildcard()
      |> Enum.each(&File.rm/1)
    end)
  end

  defp resource_key(resource),
    do: resource |> Module.split() |> Enum.map_join(".", &Macro.underscore/1)

  defp quote_name(name), do: "`#{String.replace(name, "`", "``")}`"

  defp timestamp do
    {{year, month, day}, {hour, minute, second}} = :calendar.universal_time()
    "#{year}#{pad(month)}#{pad(day)}#{pad(hour)}#{pad(minute)}#{pad(second)}"
  end

  defp pad(value), do: value |> Integer.to_string() |> String.pad_leading(2, "0")
end
