defmodule AshClickhouse.InsertTest do
  @moduledoc """
  Unit tests for AshClickhouse.DataLayer.Insert value encoding and attribute
  helpers.
  """
  use ExUnit.Case, async: true

  alias AshClickhouse.DataLayer.Insert
  alias AshClickhouse.DataLayer.Types

  defmodule BulkResource do
    use Ash.Resource,
      data_layer: AshClickhouse.DataLayer,
      domain: nil

    import AshClickhouse.DataLayer.Dsl.Macros

    clickhouse do
      table("bulk_insert")
      repo(AshClickhouse.TestRepo)
    end

    attributes do
      uuid_primary_key(:id)
      attribute(:created_at, :utc_datetime)
      attribute(:starts_at, :naive_datetime)
      attribute(:day, :date)
      attribute(:clock, :time)
      attribute(:amount, :decimal)
      attribute(:meta, :map)
      attribute(:items, {:array, :string})
    end
  end

  defmodule AutogenResource do
    use Ash.Resource,
      data_layer: AshClickhouse.DataLayer,
      domain: nil

    attributes do
      uuid_primary_key(:id)
      attribute(:code, :integer, primary_key?: true, allow_nil?: false, default: fn -> 42 end)
    end
  end

  defmodule DateTime64Ms do
    use Ash.Type.NewType, subtype_of: :utc_datetime

    def storage_type(_), do: "DateTime64(3)"
  end

  defmodule DateTime64Ns do
    use Ash.Type.NewType, subtype_of: :utc_datetime

    def storage_type(_), do: "DateTime64(9)"
  end

  defmodule PlainSecondDateTime do
    use Ash.Type.NewType, subtype_of: :utc_datetime

    def storage_type(_), do: "DateTime"
  end

  defmodule PrecisionResource do
    use Ash.Resource, data_layer: AshClickhouse.DataLayer, domain: nil

    attributes do
      uuid_primary_key(:id)
      attribute(:ms, DateTime64Ms)
      attribute(:us, :utc_datetime)
      attribute(:ns, DateTime64Ns)
      attribute(:plain, PlainSecondDateTime)
    end
  end

  defmodule InsertOptsResource do
    use Ash.Resource,
      data_layer: AshClickhouse.DataLayer,
      domain: nil

    import AshClickhouse.DataLayer.Dsl.Macros

    clickhouse do
      table("insert_opts")
      repo(AshClickhouse.TestRepo)
      insert_opts(async_insert: 1, wait_for_async_insert: 1)
    end

    attributes do
      uuid_primary_key(:id)
    end
  end

  describe "build_insert_rows/2 bulk value encoding" do
    test "encodes Date/Time/NaiveDateTime/DateTime/Decimal for JSON rows" do
      uuid = "123e4567-e89b-12d3-a456-426614174000"
      {:ok, uuid_bin} = Types.uuid_string_to_binary(uuid)

      {:ok, naive} = NaiveDateTime.from_iso8601("2024-01-02 03:04:05")
      {:ok, utc} = DateTime.from_naive(naive, "Etc/UTC")
      {:ok, time} = Time.from_iso8601("03:04:05")

      row = %{
        "id" => uuid_bin,
        "created_at" => utc,
        "starts_at" => naive,
        "day" => ~D[2024-01-02],
        "clock" => time,
        "amount" => Decimal.new("12.34"),
        "meta" => %{a: 1},
        "items" => ["x", "y"]
      }

      {fields, [encoded]} = Insert.build_insert_rows([row], BulkResource)
      values = Enum.zip(fields, encoded) |> Map.new()

      assert Enum.member?(fields, "`id`")
      assert values["`id`"] == uuid
      assert values["`created_at`"] == "1704164645.000000"
      assert values["`starts_at`"] == "1704164645.000000"
      assert values["`day`"] == 19_724
      assert values["`clock`"] == "03:04:05"
      assert values["`amount`"] == "12.34"
      assert values["`meta`"] == %{a: 1}
      assert values["`items`"] == ["x", "y"]
    end

    test "keeps 36-character UUID strings as-is in bulk rows" do
      uuid = "123e4567-e89b-12d3-a456-426614174000"

      {_fields, [encoded]} = Insert.build_insert_rows([%{"id" => uuid}], BulkResource)
      assert encoded == [uuid, nil, nil, nil, nil, nil, nil, nil]
    end
  end

  describe "encode_attr_value/4" do
    test "leaves a non-UUID-string value for a uuid column unchanged" do
      uuid_fields = MapSet.new([:id, "id"])
      assert Insert.encode_attr_value(:id, "not-a-uuid", %{}, uuid_fields) == "not-a-uuid"
    end

    test "passes through values for columns not present in the attribute map" do
      assert Insert.encode_attr_value(:ghost, "x", %{}, MapSet.new()) == "x"
    end
  end

  describe "get_primary_key_from_changeset/2" do
    test "skips primary keys missing from the changeset data" do
      assert Insert.get_primary_key_from_changeset(%{data: %{}}, BulkResource) == %{}
    end
  end

  describe "changeset_to_insert_attrs/2" do
    test "fills in a missing pk with an autogenerated value" do
      attrs = Insert.changeset_to_insert_attrs(%{attributes: %{}}, AutogenResource)
      assert is_integer(attrs[:code])
    end
  end

  describe "insert_opts/2" do
    test "merges configured async insert opts" do
      opts = Insert.insert_opts(InsertOptsResource, [])

      assert opts[:async_insert] == 1
      assert opts[:wait_for_async_insert] == 1
    end

    test "drops Ash-internal bulk keys" do
      opts =
        Insert.insert_opts(InsertOptsResource,
          return_records?: true,
          batch_size: 5,
          authorize?: true,
          tenant: "t",
          async_insert: 1
        )

      assert opts[:async_insert] == 1
      refute Keyword.has_key?(opts, :return_records?)
      refute Keyword.has_key?(opts, :batch_size)
      refute Keyword.has_key?(opts, :authorize?)
      refute Keyword.has_key?(opts, :tenant)
    end
  end

  describe "DateTime64 decimal Unix-seconds encoding" do
    test "encodes DateTime64 as decimal Unix-seconds strings and plain DateTime as epoch seconds" do
      {:ok, dt, _} = DateTime.from_iso8601("2024-01-02T03:04:05Z")

      {_fields, [encoded]} =
        Insert.build_insert_rows(
          [%{"ms" => dt, "us" => dt, "ns" => dt, "plain" => dt}],
          PrecisionResource
        )

      assert encoded == [
               nil,
               "1704164645.000000",
               "1704164645.000000",
               "1704164645.000000",
               1_704_164_645
             ]
    end

    test "preserves microseconds in the decimal-Unix-seconds value" do
      {:ok, dt, _} = DateTime.from_iso8601("2024-01-02T03:04:05.123456Z")

      {_fields, [encoded]} = Insert.build_insert_rows([%{"us" => dt}], PrecisionResource)

      assert [nil, nil, value, nil, nil] = encoded
      assert value == "1704164645.123456"
    end

    test "DateTime64 values are JSON strings, not numbers or integer tick counts" do
      {:ok, dt, _} = DateTime.from_iso8601("2024-01-02T03:04:05Z")

      {_fields, [encoded]} = Insert.build_insert_rows([%{"us" => dt}], PrecisionResource)

      assert [nil, nil, value, nil, nil] = encoded
      assert is_binary(value)
      refute is_number(value)
    end

    test "every DateTime64 precision uses the identical decimal Unix-seconds string" do
      {:ok, dt, _} = DateTime.from_iso8601("2024-01-02T03:04:05.123456Z")

      {_fields, [encoded]} =
        Insert.build_insert_rows(
          [%{"ms" => dt, "us" => dt, "ns" => dt}],
          PrecisionResource
        )

      assert [nil, "1704164645.123456", "1704164645.123456", "1704164645.123456", nil] =
               encoded
    end

    test "encodes pre-1970 instants as signed decimal Unix seconds" do
      {:ok, dt, _} = DateTime.from_iso8601("1969-12-31T23:59:59.876544Z")

      {_fields, [encoded]} = Insert.build_insert_rows([%{"us" => dt}], PrecisionResource)

      assert [nil, nil, value, nil, nil] = encoded
      assert value == "-0.123456"
    end

    test "NaiveDateTime encodes identically to its UTC DateTime equivalent" do
      {:ok, naive} = NaiveDateTime.from_iso8601("2024-01-02T03:04:05.123456")
      {:ok, dt} = DateTime.from_naive(naive, "Etc/UTC")

      {_fields, [encoded_naive]} =
        Insert.build_insert_rows([%{"us" => naive}], PrecisionResource)

      {_fields, [encoded_dt]} =
        Insert.build_insert_rows([%{"us" => dt}], PrecisionResource)

      assert encoded_naive == encoded_dt
    end
  end
end
