defmodule AshClickhouse.InsertTest do
  @moduledoc """
  Unit tests for AshClickhouse.DataLayer.Insert value encoding and attribute
  helpers.
  """
  use ExUnit.Case, async: true

  alias AshClickhouse.DataLayer.Insert
  alias AshClickhouse.DataLayer.Types

  defmodule BulkResource do
    use Ash.Resource,
      data_layer: AshClickhouse.DataLayer,
      domain: nil

    import AshClickhouse.DataLayer.Dsl.Macros

    clickhouse do
      table("bulk_insert")
      repo(AshClickhouse.TestRepo)
    end

    attributes do
      uuid_primary_key(:id)
      attribute(:created_at, :utc_datetime)
      attribute(:starts_at, :naive_datetime)
      attribute(:day, :date)
      attribute(:clock, :time)
      attribute(:amount, :decimal)
      attribute(:meta, :map)
      attribute(:items, {:array, :string})
    end
  end

  defmodule AutogenResource do
    use Ash.Resource,
      data_layer: AshClickhouse.DataLayer,
      domain: nil

    attributes do
      uuid_primary_key(:id)
      attribute(:code, :integer, primary_key?: true, allow_nil?: false, default: fn -> 42 end)
    end
  end

  defmodule InsertOptsResource do
    use Ash.Resource,
      data_layer: AshClickhouse.DataLayer,
      domain: nil

    import AshClickhouse.DataLayer.Dsl.Macros

    clickhouse do
      table("insert_opts")
      repo(AshClickhouse.TestRepo)
      insert_opts(async_insert: 1, wait_for_async_insert: 1)
    end

    attributes do
      uuid_primary_key(:id)
    end
  end

  describe "build_insert_rows/2 bulk value encoding" do
    test "encodes Date/Time/NaiveDateTime/DateTime/Decimal for JSON rows" do
      uuid = "123e4567-e89b-12d3-a456-426614174000"
      {:ok, uuid_bin} = Types.uuid_string_to_binary(uuid)

      {:ok, naive} = NaiveDateTime.from_iso8601("2024-01-02 03:04:05")
      {:ok, utc} = DateTime.from_naive(naive, "Etc/UTC")
      {:ok, time} = Time.from_iso8601("03:04:05")

      row = %{
        "id" => uuid_bin,
        "created_at" => utc,
        "starts_at" => naive,
        "day" => ~D[2024-01-02],
        "clock" => time,
        "amount" => Decimal.new("12.34"),
        "meta" => %{a: 1},
        "items" => ["x", "y"]
      }

      {fields, [encoded]} = Insert.build_insert_rows([row], BulkResource)
      values = Enum.zip(fields, encoded) |> Map.new()

      assert Enum.member?(fields, "`id`")
      assert values["`id`"] == uuid
      assert values["`created_at`"] == 1_704_164_645
      assert values["`starts_at`"] == 1_704_164_645
      assert values["`day`"] == 739_252
      assert values["`clock`"] == 11_045
      assert values["`amount`"] == "12.34"
      assert values["`meta`"] == %{a: 1}
      assert values["`items`"] == ["x", "y"]
    end

    test "keeps 36-character UUID strings as-is in bulk rows" do
      uuid = "123e4567-e89b-12d3-a456-426614174000"

      {_fields, [encoded]} = Insert.build_insert_rows([%{"id" => uuid}], BulkResource)
      assert encoded == [uuid, nil, nil, nil, nil, nil, nil, nil]
    end
  end

  describe "encode_attr_value/4" do
    test "leaves a non-UUID-string value for a uuid column unchanged" do
      uuid_fields = MapSet.new([:id, "id"])
      assert Insert.encode_attr_value(:id, "not-a-uuid", %{}, uuid_fields) == "not-a-uuid"
    end

    test "passes through values for columns not present in the attribute map" do
      assert Insert.encode_attr_value(:ghost, "x", %{}, MapSet.new()) == "x"
    end
  end

  describe "get_primary_key_from_changeset/2" do
    test "skips primary keys missing from the changeset data" do
      assert Insert.get_primary_key_from_changeset(%{data: %{}}, BulkResource) == %{}
    end
  end

  describe "changeset_to_insert_attrs/2" do
    test "fills in a missing pk with an autogenerated value" do
      attrs = Insert.changeset_to_insert_attrs(%{attributes: %{}}, AutogenResource)
      assert is_integer(attrs[:code])
    end
  end

  describe "insert_opts/2" do
    test "merges configured async insert opts" do
      opts = Insert.insert_opts(InsertOptsResource, [])

      assert opts[:async_insert] == 1
      assert opts[:wait_for_async_insert] == 1
    end
  end
end
